[project]
name = "lattice"
version = "0.1.0"
description = "Alternative locally running OSS frontend for W&B."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask==3.0.3",
    "wandb==0.18.7",
]

[tool.uv]
package = false
